name: Publish
# This workflow is triggered on pushes to the repository.
on:
  release:
    branches: [ master ]

jobs:
  package:
    name: Create Package
    steps:
      - name: bigwigs_packager
        uses: BigWigsMods/packager@master
    env:
      # This section might already create other env variables, just append the WAGO_API_TOKEN to these
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}